#!/usr/bin/env python3
"""Generate every Mayonaka launcher asset from a single geometry definition.

The neko mark is defined once as a list of cubic Bezier subpaths in the 108x108 adaptive-icon
viewport. From that one definition this script emits:

  * app/src/main/res/drawable/ic_launcher_foreground.xml -- the adaptive icon foreground and,
    via <monochrome>, the themed-icon mask.
  * app/src/main/res/mipmap-{m,h,xh,xxh,xxx}dpi/ic_launcher.png      -- legacy square icons.
  * app/src/main/res/mipmap-{m,h,xh,xxh,xxx}dpi/ic_launcher_round.png -- legacy round icons.
  * app/src/main/res/drawable/banner.png                            -- the Android TV banner.

Vector and raster therefore never drift apart. Requires Pillow:  pip install Pillow

    python3 art/generate_icons.py
"""

import math
import os
import sys

from PIL import Image, ImageDraw

BACKGROUND = (0x0A, 0x0A, 0x0F, 255)   # #0a0a0f
ACCENT = (0x8B, 0x5C, 0xF6, 255)       # #8B5CF6

VIEWPORT = 108.0

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES = os.path.join(REPO_ROOT, "app", "src", "main", "res")

# --------------------------------------------------------------------------------------------
# Geometry
# --------------------------------------------------------------------------------------------
#
# Each subpath is (start_point, [(control1, control2, end), ...]). Coordinates live in the
# 108x108 adaptive-icon viewport; the launcher only guarantees the central 72x72 is visible, so
# the mark is kept inside roughly x,y in [20, 88].

def _ellipse(cx, cy, rx, ry):
    """A closed ellipse as four cubic Bezier segments."""
    k = 0.5522847498
    return (
        (cx, cy - ry),
        [
            ((cx + rx * k, cy - ry), (cx + rx, cy - ry * k), (cx + rx, cy)),
            ((cx + rx, cy + ry * k), (cx + rx * k, cy + ry), (cx, cy + ry)),
            ((cx - rx * k, cy + ry), (cx - rx, cy + ry * k), (cx - rx, cy)),
            ((cx - rx, cy - ry * k), (cx - rx * k, cy - ry), (cx, cy - ry)),
        ],
    )


# The head: left ear tip, down the left cheek, round the chin, up the right cheek to the right
# ear tip, then back down into the skull and across the dip between the ears.
HEAD = (
    (26.0, 19.0),
    [
        ((25.0, 33.0), (23.5, 44.0), (23.5, 56.0)),      # left outer edge
        ((23.5, 74.5), (37.0, 88.5), (54.0, 88.5)),      # left cheek into the chin
        ((71.0, 88.5), (84.5, 74.5), (84.5, 56.0)),      # chin into the right cheek
        ((84.5, 44.0), (83.0, 33.0), (82.0, 19.0)),      # right outer edge up to the ear tip
        ((77.5, 24.5), (70.0, 30.5), (65.0, 35.5)),      # inner right ear
        ((61.5, 33.8), (57.9, 33.0), (54.0, 33.0)),      # dip between the ears
        ((50.1, 33.0), (46.5, 33.8), (43.0, 35.5)),
        ((38.0, 30.5), (30.5, 24.5), (26.0, 19.0)),      # inner left ear, back to the tip
    ],
)

# Eyes and nose are holes punched out of the head with the even-odd fill rule, so the themed
# (monochrome) icon keeps them as transparency instead of flat colour.
LEFT_EYE = _ellipse(42.0, 57.0, 5.4, 7.6)
RIGHT_EYE = _ellipse(66.0, 57.0, 5.4, 7.6)

NOSE = (
    (54.0, 74.0),
    [
        ((51.2, 74.0), (49.0, 71.9), (49.0, 69.4)),
        ((49.0, 68.2), (50.0, 67.4), (51.2, 67.4)),
        ((56.8, 67.4), (56.8, 67.4), (56.8, 67.4)),
        ((58.0, 67.4), (59.0, 68.2), (59.0, 69.4)),
        ((59.0, 71.9), (56.8, 74.0), (54.0, 74.0)),
    ],
)

SUBPATHS = [HEAD, LEFT_EYE, RIGHT_EYE, NOSE]


# --------------------------------------------------------------------------------------------
# Vector drawable
# --------------------------------------------------------------------------------------------

def _n(v):
    """Format a coordinate the way a hand-written vector drawable would."""
    s = "%.2f" % v
    s = s.rstrip("0").rstrip(".")
    return s if s else "0"


def path_data():
    out = []
    for start, segments in SUBPATHS:
        out.append("M%s,%s" % (_n(start[0]), _n(start[1])))
        for c1, c2, end in segments:
            out.append("C%s,%s %s,%s %s,%s" % (
                _n(c1[0]), _n(c1[1]), _n(c2[0]), _n(c2[1]), _n(end[0]), _n(end[1])))
        out.append("Z")
    return " ".join(out)


VECTOR_TEMPLATE = """<?xml version="1.0" encoding="utf-8"?>
<!--
 Mayonaka neko mark. Generated by art/generate_icons.py - edit the geometry there, not here.
 Used as both the adaptive icon foreground and the monochrome (themed icon) layer, so it is a
 single even-odd path: the eyes and nose are holes, not painted shapes.
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">

    <path
        android:fillColor="#8B5CF6"
        android:fillType="evenOdd"
        android:pathData="%s" />

</vector>
"""


def write_vector():
    path = os.path.join(RES, "drawable", "ic_launcher_foreground.xml")
    with open(path, "w") as f:
        f.write(VECTOR_TEMPLATE % path_data())
    print("wrote", os.path.relpath(path, REPO_ROOT))


NOTIFICATION_TEMPLATE = """<?xml version="1.0" encoding="utf-8"?>
<!--
 Mayonaka notification icon. Generated by art/generate_icons.py - edit the geometry there.
 Status bar icons are treated as alpha masks and tinted by the system, so this is the same neko
 mark painted white and scaled from the 108 viewport down into 24dp with a little padding.
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">

    <group
        android:scaleX="%(scale)s"
        android:scaleY="%(scale)s"
        android:translateX="%(translate)s"
        android:translateY="%(translate)s">
        <path
            android:fillColor="#FFFFFFFF"
            android:fillType="evenOdd"
            android:pathData="%(path)s" />
    </group>

</vector>
"""


def write_notification_icon():
    # 20dp of the 24dp canvas, centred, which is what the Material status bar grid asks for.
    scale = 20.0 / VIEWPORT
    translate = (24.0 - VIEWPORT * scale) / 2.0
    path = os.path.join(RES, "drawable", "ic_service_notification.xml")
    with open(path, "w") as f:
        f.write(NOTIFICATION_TEMPLATE % {
            "scale": "%.5f" % scale,
            "translate": "%.5f" % translate,
            "path": path_data(),
        })
    print("wrote", os.path.relpath(path, REPO_ROOT))


# --------------------------------------------------------------------------------------------
# Raster
# --------------------------------------------------------------------------------------------

def _flatten(start, segments, steps=48):
    """Flatten a subpath's cubic Beziers into a polygon."""
    points = [start]
    current = start
    for c1, c2, end in segments:
        for i in range(1, steps + 1):
            t = i / float(steps)
            u = 1.0 - t
            x = (u * u * u * current[0] + 3 * u * u * t * c1[0]
                 + 3 * u * t * t * c2[0] + t * t * t * end[0])
            y = (u * u * u * current[1] + 3 * u * u * t * c1[1]
                 + 3 * u * t * t * c2[1] + t * t * t * end[1])
            points.append((x, y))
        current = end
    return points


SUPERSAMPLE = 8


def render_mark(size, scale, offset_y=0.0):
    """Render the violet mark on a transparent canvas of `size` px.

    `scale` is the fraction of the canvas the 108x108 viewport occupies.
    """
    ss = size * SUPERSAMPLE
    img = Image.new("RGBA", (ss, ss), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)

    unit = ss * scale / VIEWPORT
    pad = (ss - VIEWPORT * unit) / 2.0

    def project(points):
        return [(pad + x * unit, pad + (y + offset_y) * unit) for x, y in points]

    # The head is painted, then the holes are erased, which reproduces the even-odd fill of the
    # vector drawable.
    draw.polygon(project(_flatten(*HEAD)), fill=ACCENT)
    for hole in (LEFT_EYE, RIGHT_EYE, NOSE):
        draw.polygon(project(_flatten(*hole)), fill=(0, 0, 0, 0))

    return img.resize((size, size), Image.LANCZOS)


def rounded_square(size, radius_ratio=0.22):
    img = Image.new("RGBA", (size * SUPERSAMPLE,) * 2, (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    r = int(size * SUPERSAMPLE * radius_ratio)
    draw.rounded_rectangle([0, 0, size * SUPERSAMPLE - 1, size * SUPERSAMPLE - 1],
                           radius=r, fill=BACKGROUND)
    return img.resize((size, size), Image.LANCZOS)


def circle(size):
    img = Image.new("RGBA", (size * SUPERSAMPLE,) * 2, (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    draw.ellipse([0, 0, size * SUPERSAMPLE - 1, size * SUPERSAMPLE - 1], fill=BACKGROUND)
    return img.resize((size, size), Image.LANCZOS)


DENSITIES = [("mdpi", 48), ("hdpi", 72), ("xhdpi", 96), ("xxhdpi", 144), ("xxxhdpi", 192)]


def write_legacy_icons():
    for density, size in DENSITIES:
        out_dir = os.path.join(RES, "mipmap-" + density)
        os.makedirs(out_dir, exist_ok=True)

        # Legacy icons have no safe-zone crop, so the mark can use more of the canvas than the
        # 72/108 the adaptive icon reserves.
        mark = render_mark(size, scale=0.86)

        square = rounded_square(size)
        square.alpha_composite(mark)
        square.save(os.path.join(out_dir, "ic_launcher.png"))

        round_icon = circle(size)
        round_icon.alpha_composite(render_mark(size, scale=0.78))
        round_icon.save(os.path.join(out_dir, "ic_launcher_round.png"))

        print("wrote", os.path.relpath(out_dir, REPO_ROOT), "(%dx%d)" % (size, size))


def write_banner():
    """Android TV banner: 320x180, mark on the left, wordmark-free (the label sits under it)."""
    w, h = 320, 180
    img = Image.new("RGBA", (w, h), BACKGROUND)
    mark = render_mark(h, scale=0.62)
    img.alpha_composite(mark, (int((w - h) / 2), 0))
    path = os.path.join(RES, "drawable", "banner.png")
    img.convert("RGB").save(path)
    print("wrote", os.path.relpath(path, REPO_ROOT))


def main():
    if not os.path.isdir(RES):
        sys.exit("resource directory not found: " + RES)
    write_vector()
    write_notification_icon()
    write_legacy_icons()
    write_banner()


if __name__ == "__main__":
    main()
